---
layout: page
title: "한국 코로나19"
subtitle: "코로나 바이러스 3D"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "코로나", "코로나19", "covid-19", "corona", "3D"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_corona.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


# 가자 메타버스 [^corona-shiny] {#metaverse-covid19} 

[^corona-shiny]: [Meinhard Ploner (Mar 22, 2020), "Create your Own Coronavirus in 3D - Zoom and rotate your own COVID-19 —in 20 lines of code", Analytics Vidhya](https://medium.com/analytics-vidhya/create-your-own-coronavirus-in-3d-37d1ac5a5437)

```{r read-corona, webgl=TRUE, eval = FALSE}
library(tidyverse)
library(rgl)
library(readobj)

corona_mdl <- read.obj("data/coronavirus.obj", convert.rgl=TRUE)

open3d()
shade3d(corona_mdl$Layer_1, color="darkgray")
shade3d(corona_mdl$Layer_2, color="red")
bg3d(gray(level=0.95))
rglwidget(reuse=TRUE)
```


