---
layout: page
title: "한국 코로나19"
subtitle: "탐색적 데이터 분석 (EDA)"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "코로나", "코로나19", "covid-19", "corona"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_corona.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```



# 성별, 연령별 {#clean-corona-dataset}

공공데이터 포털에서 [데이터 가져오기](ingest-data.html)를 통해 입수한 데이터를 후속 시각화와 모형개발 작업을 위해 깔끔한 정제작업을 수행한다. 특히, 2020-11-06 중복된 행이 포함되어 중복 제거작업을 선행하여 처리한다.
2020-04-02 ~ 2020-04-06 사이 결측값이 있어 `pad_by_time()` 함수로 결측된 기간을 생성시키고 나서,
`ts_impute_vec()` 함수로 선형보간(`period = 1`)을 통해 결측값을 채워넣어 정제작업이 완료된 데이터를 가지고 탐색적 데이터 작업을 수행한다.


```{r EDA-age-confirmed}
library(tidyverse)
library(httr)
library(rvest)
library(glue)
library(lubridate)

covid_age_gender_df <- read_rds("data/covid_age_gender_clean.rds")

covid_age_gender_df
```

# 추세 {#EDA-trend}

탐색적 데이터 분석을 통해 전반적인 추세를 살펴봄으로 인해 숨겨진 데이터의 오류도 찾아낼 수 있다.

```{r EDA-trend}
library(timetk)

covid_age_daily_df <- covid_age_gender_df %>% 
  filter(날짜 >= "2020-04-09") %>% 
  filter(!str_detect(구분, pattern = "(남성)|(여성)")) %>% 
  timetk::summarise_by_time(.date_var = 날짜, 
                            .by = "day", 
                            누적검사자 = sum(검사자),
                            누적확진자 = sum(확진자),
                            누적사망자 = sum(사망자)
                            ) %>% 
  mutate(누적사망자 = ifelse(between_time(날짜, start_date = "2020-08-02", end_date = "2020-08-03"), 301, 누적사망자),
         누적사망자 = ifelse(날짜 == "2020-06-23", 280, 누적사망자)) %>% 
  mutate(검사자 = 누적검사자 - lag(누적검사자, n = 1L),
         확진자 = 누적확진자 - lag(누적확진자, n = 1L),
         사망자 = 누적사망자 - lag(누적사망자, n = 1L))


covid_age_daily_df %>% 
  select(-contains("누적")) %>% 
  pivot_longer(-날짜) %>% 
  plot_time_series(.date_var   = 날짜, 
                   .value      = value,
                   .facet_var  = name,
                   .facet_ncol = 2)

covid_age_gender_df %>% 
  arrange(날짜)

```

# 연령별 치명률 {#mortality}

```{r}
covid_age_gender_df %>% 
  mutate(치명율 = 치명율 * 100) %>% 
  filter(!str_detect(구분, pattern = "(남성)|(여성)")) %>% 
  filter(!str_detect(구분, "(0-11)|(0-9)|(10-19)|(20-29)|(30-39)|(40-49)")) %>% 
  timetk::plot_time_series(.date_var     = 날짜, 
                           .value        = 치명율, 
                           .facet_var    = 구분,
                           .interactive  = FALSE,
                           .smooth       = FALSE,
                           .facet_ncol   = 4,
                           .facet_scales = "fixed")

```

