---
layout: page
title: "한국 코로나19"
subtitle: "데이터 가져오기 - 팩키지(`COVID19`)"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "코로나", "코로나19", "covid-19", "corona"]
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_corona.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```



# `COVID19` 팩키지 [^pkg-covid] {#get-pkg-corona-dataset}

[^pkg-covid]: [COVID19: R Interface to COVID-19 Data Hub](https://cran.r-project.org/web/packages/COVID19/)

[`COVID19`](https://cran.r-project.org/web/packages/COVID19/) 팩키지를 통해 대한민국을 비롯한 각국 코로나19 데이터를 손쉽고 정확하게 얻을 수 있다 [@Guidotti2020]. 
데이터가 상당히 깔끔하기 때문에 기본적인 데이터 정제작업을 수행한다.

- 초기 일별 검사자수에 결측값이 있어 선형보간 작업을 수행한다.
- 회복자와 사망자에 초기 `NA` 값은 0으로 합리적으로 추정하여 보정한다.

```{r pkg-COVID19}
# install.packages("COVID19")
library(tidyverse)
library(COVID19)
library(timetk)

korea_dat <- covid19("KOR", level = 1)

korea_df <- korea_dat %>% 
  ungroup() %>% 
  dplyr::select(날짜=date, 누적검사자=tests, 누적확진자=confirmed, 누적회복자=recovered, 누적사망자=deaths) %>% 
  timetk::pad_by_time(.date_var = 날짜, .by = "day", .pad_value = NA) %>% 
  mutate(누적검사자 = timetk::ts_impute_vec(누적검사자, period = 1) %>%  ceiling(.),
         누적회복자 = ifelse(is.na(누적회복자), 0, 누적회복자),
         누적사망자 = ifelse(is.na(누적사망자), 0, 누적사망자))

korea_df %>% 
  reactable::reactable()

korea_df %>% 
  write_rds("data/COVID_korea.rds")
```


